---
title: "Lab 1"
author: "An Bui"
date: "10 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Objectives:

- basic review (data wrangling)  
- intro to spatial data in R with `sf`  
- intro to Shiny apps  

#### 1. Attach packages
```{r set up packages, include = FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(tmap)
```

#### 2. Review: reading, exploring, warngling, visualizing data
##### a. Read in data.
```{r read in wine data, include = FALSE}
wine <- read_csv("wine_data.csv")
```

##### b. Wrangle data.
```{r wrangling, include = FALSE}
#### make new data set ####
# use original data set wine
wine_new <- wine %>%
  # select desired columns
  select(country, province, winery, region_1, points, price) %>% 
  # rename province column name to state
  rename(state = province) %>%
  # filter rows to only include California, Oregon, and Washington data
  filter(state == "California" |
           state == "Oregon" |
           state == "Washington") %>% 
  # add column for best price per points
  mutate(ppd = points/price) %>% 
  # arrange by decreasing points/dollar
  arrange(-ppd)
```

##### c. Use group_by() and summarize() to find summary statistics by group.
```{r summary statistics}
# make summary table from wine_new
wine_summary <- wine_new %>% 
  # create groups by state
  # btw you can group_by() for multiple columns
  group_by(state) %>% 
  # summary statistics, remove any NA values
  summarize(
    mean_ppd = mean(ppd, na.rm = TRUE),
    max_ppd = max(ppd, na.rm = TRUE)
  )
```

##### d. Visualize data.
```{r create plots, echo = FALSE}







```











